Make flash and ram size depend on the mcu feature
stm32-rs/stm32l0xx-hal pull request #173
Opened 2021-06-10 15:52 UTC by azerupi

This fixes #170 by adding features for flash and RAM sizes and enabling the appropriate one for each mcu feature. It uses the new output from dbrgn/cube-parse#5 

I'm not sure why I have more MCUs in the list, maybe a more recent version of CubeMX?
I tested it out locally, it seems to work.

Also I think this is a **breaking change**. Because it might break code that does not select a `mcu-*` feature but selects the other features manually. In that case no memory.x file will be loaded and the build will fail.

2021-06-11 11:20 UTC, hannobraun reviewed
Looks good to me, although I didn't test or check against data sheets. I'd like to hear @dbrgn's opinion, as he's the resident CubeMX expert.

2021-06-11 11:40 UTC, azerupi commented
No problem, it's better to take the time to review and test this :slightly_smiling_face: 

I just realized I didn't remove the memory_l0x*.x files, so I'll do that before it gets merged. 

On an unrelated note, I was wondering what config you guys where using for rust-analyzer? I've added the following `.vscode/settings.json` file, but I'm wondering if you have more elaborate configurations that work better?
```json
{
    "rust-analyzer.cargo.features": ["mcu-STM32L071K8Ux"],
}
```

2021-06-12 09:56 UTC, dbrgn commented
> Looks good to me, although I didn't test or check against data sheets. I'd like to hear @dbrgn's opinion, as he's the resident CubeMX expert.

🙂 I'll take a look as soon as I can.

2021-06-14 08:21 UTC, hannobraun commented
> On an unrelated note, I was wondering what config you guys where using for rust-analyzer? I've added the following `.vscode/settings.json` file, but I'm wondering if you have more elaborate configurations that work better?

It's actually been a while since I actively worked on this repository, and I don't have an active checkout. I do have `"rust-analyzer.checkOnSave.allTargets": false`, in addition to the `cargo.features`, in the configuration for another HAL. But I don't remember why I needed that.

2021-06-23 21:42 UTC, dbrgn commented
> I'm not sure why I have more MCUs in the list, maybe a more recent version of CubeMX?

I think so, yes! I updated the list with the old version of cube-parse in #178. Can you rebase against the current `master` branch and resolve the conflicts by simply overwriting the conflicting part with the generated features? That way, only the new `ram-*` and `flash-*` feature changes should remain.

In case you're unsure how to do this with git, don't hesitate to ask, I'm happy to help!

2021-06-23 21:50 UTC, dbrgn requested changes
Two small suggestions for the README, otherwise this looks good to me! Thanks for implementing this change, I think it will be very useful to get started quickly.

2021-06-23 21:50 UTC, dbrgn commented on README.md
> +Flash and RAM sizes are configured for each mcu in the feature list.
I'd slightly reword this:

```suggestion
Flash and RAM sizes are automatically configured by using the appropriate
`mcu-*` Cargo feature, as described further up.
```

2021-06-23 21:50 UTC, dbrgn commented on README.md
> +the `memory.x` of `stm32l0xx-hal` by providing your own.
Slight improvement (hopefully):

```suggestion
If you have an MCU that does not yet have a corresponding `mcu-*` feature, or
if the default configuration is incorrect, you can override the `memory.x` of
`stm32l0xx-hal` by providing your own:
```

2021-06-23 21:50 UTC, dbrgn commented on build.rs
> +        .collect();
Nice way to avoid an if-festival! 👍🏻

2021-06-24 17:09 UTC, azerupi commented
Sorry for the noise, I think I forgot to add a file when rebasing. It should be good now.

2021-06-25 12:42 UTC, dbrgn approved these changes
Thanks! An intermediate commit adds git conflict markers (which are then removed again in the next commit), but we can solve that quite easily by squashing 🙂

2021-06-25 12:43 UTC, merged